### ISSUE TITLE
interesting fork you may wish to peruse!

### ISSUE THREAD

**Issue by agentdavo** [michaelforney/tinyemu#1]
https://github.com/fernandotcl/TinyEMU

Added...

    Support for loading ELF images
    Support for loading initrd images or compressed initramfs archives
    Framebuffer support through SDL 2 instead of 1.2.

**Comment by michaelforney** [comment]
Thanks for the info! When I mess around with tinyemu again I'll definitely look at that repository.

(going through old issues that I'd missed)
